web:
  image: nginx:latest
  ports:
      - "8080:80"
  volumes:
    - ../test_repo:/test_repo
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
      - php
php:
  image: php:7.2-fpm
  volumes:
    - ../test_repo:/test_repo